from __future__ import annotations

import os
from pathlib import Path
from typing import Iterable

from dotenv import load_dotenv

_ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = _ROOT / ".env"
ENV_EXAMPLE_PATH = _ROOT / ".env.example"
_VERBOSE_ENV = "AUTOCUT_VERBOSE"
_FALSE_VALUES = {"0", "false", "no", "off", "n", "f"}

# Keys managed by the GUI setup tab. Values are kept as plain strings so they
# can be written back to .env without surprising conversions.
ENV_FIELDS: tuple[tuple[str, str, str], ...] = (
    ("AUTOCUT_BACKEND", "預設後端", "local-api"),
    ("LOCAL_API_BASE", "Local API Base", "http://0.0.0.0:8080"),
    ("LOCAL_API_MODEL", "Local API Model", ""),
    ("AUTOCUT_SCRIPT_API_BASE", "腳本 API Base", "http://localhost:8080"),
    ("AUTOCUT_SCRIPT_API_KEY", "腳本 API Key", "not-needed"),
    ("AUTOCUT_SCRIPT_API_MODEL", "腳本 API Model", ""),
    ("AUTOCUT_SCRIPT_API_MAX_TOKENS", "腳本 Max Tokens", ""),
    ("AUTOCUT_CAPTION_DURATION_SECONDS", "字幕秒數", "3"),
    ("AUTOCUT_MUSIC_DIR", "音樂資料夾", ""),
    ("AUTOCUT_MUSIC_VOLUME", "背景音樂音量", "0.18"),
    ("AUTOCUT_OPENING_CAPTION_FONT", "字幕字型檔", ""),
    ("AUTOCUT_VERBOSE", "詳細日誌", "true"),
)


def reload_env() -> None:
    """Reload project .env into os.environ for the current GUI process."""
    load_dotenv(ENV_PATH, override=True)


def is_verbose_enabled() -> bool:
    """Return whether detailed logging is enabled for GUI-launched jobs.

    Detailed logging defaults to on for every mode. Set AUTOCUT_VERBOSE=false
    (also accepts 0/no/off/n/f) in .env to disable it.
    """
    reload_env()
    value = os.environ.get(_VERBOSE_ENV)
    if value is None:
        return True
    return value.strip().lower() not in _FALSE_VALUES


def parse_env_file(path: Path = ENV_PATH) -> dict[str, str]:
    """Parse simple KEY=VALUE lines from .env while ignoring comments/blanks."""
    values: dict[str, str] = {}
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except FileNotFoundError:
        return values
    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        key = key.strip()
        if not key:
            continue
        values[key] = _unquote_env_value(value.strip())
    return values


def _unquote_env_value(value: str) -> str:
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
        inner = value[1:-1]
        if value[0] == '"':
            inner = inner.replace(r"\n", "\n").replace(r"\r", "\r").replace(r"\t", "\t")
            inner = inner.replace(r'\"', '"').replace(r"\\", "\\")
        return inner
    return value


def load_env_values(keys: Iterable[str] | None = None) -> dict[str, str]:
    wanted = set(keys or [field[0] for field in ENV_FIELDS])
    file_values = parse_env_file(ENV_PATH)
    example_values = parse_env_file(ENV_EXAMPLE_PATH)
    defaults = {key: default for key, _label, default in ENV_FIELDS}
    values: dict[str, str] = {}
    for key in wanted:
        values[key] = file_values.get(key, example_values.get(key, os.environ.get(key, defaults.get(key, ""))))
    return values


def write_env_values(values: dict[str, str], path: Path = ENV_PATH) -> None:
    """Update .env with the provided values, preserving unrelated lines."""
    try:
        existing_lines = path.read_text(encoding="utf-8").splitlines()
    except FileNotFoundError:
        existing_lines = [
            "# auto360Cut environment configuration",
            "# Generated by GUI setup.",
            "",
        ]

    seen: set[str] = set()
    new_lines: list[str] = []
    for line in existing_lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in line:
            new_lines.append(line)
            continue
        key = line.split("=", 1)[0].strip()
        if key in values:
            new_lines.append(f"{key}={_quote_env_value(values[key])}")
            seen.add(key)
        else:
            new_lines.append(line)

    missing = [key for key, _label, _default in ENV_FIELDS if key in values and key not in seen]
    if missing:
        if new_lines and new_lines[-1].strip():
            new_lines.append("")
        new_lines.append("# --- Managed by autoCut GUI setup ---")
        for key in missing:
            new_lines.append(f"{key}={_quote_env_value(values[key])}")

    path.write_text("\n".join(new_lines).rstrip() + "\n", encoding="utf-8")
    reload_env()


def _quote_env_value(value: str) -> str:
    value = str(value).strip()
    if value == "":
        return ""
    if any(ch.isspace() for ch in value) or "#" in value or "=" in value or '"' in value:
        escaped = value.replace("\\", "\\\\").replace('"', r'\"')
        return f'"{escaped}"'
    return value
